name: GitHub metrics as SVG image
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: "master"
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
      - name: Personal metrics
        uses: lowlighter/metrics@master
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, activity, community, repositories"
          plugin_lines: yes
          plugin_music: yes
          plugin_music_playlist: ${{ secrets.MUSIC_PLAYLIST }}
          plugin_music_limit: 2
          plugin_isocalendar: yes
          plugin_topics: yes
          plugins_errors_fatal: yes

      - name: Personal metrics (detailed)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.detailed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "metadata"
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_habits: yes
          plugin_gists: yes
          plugin_followup: yes
          plugin_languages: yes
          plugin_posts: yes
          plugin_posts_source: dev.to
          plugins_errors_fatal: yes

  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Classic template
        uses: lowlighter/metrics@master
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: "header, repositories"
          plugin_lines: yes
          plugins_errors_fatal: yes

      - name: Terminal template
        uses: lowlighter/metrics@master
        with:
          template: terminal
          filename: metrics.terminal.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: "header, metadata"
          plugins_errors_fatal: yes

      - name: PageSpeed plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.pagespeed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugins_errors_fatal: yes

      - name: PageSpeed plugin (detailed)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.pagespeed.detailed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugins_errors_fatal: yes

      - name: Music plugin (playlist)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.music.playlist.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: ""
          plugin_music: yes
          plugin_music_mode: playlist
          plugin_music_playlist: ${{ secrets.MUSIC_PLAYLIST }}
          plugin_music_limit: 2
          plugins_errors_fatal: yes

      - name: Music plugin (recent)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.music.recent.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_limit: 2
          plugins_errors_fatal: yes

      - name: Habits plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: ""
          plugin_habits: yes
          plugins_errors_fatal: yes

      - name: Languages plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: ""
          plugin_languages: yes
          plugins_errors_fatal: yes

      - name: Follow-up plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: ""
          plugin_followup: yes
          plugins_errors_fatal: yes

      - name: Lines plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: "repositories"
          plugin_lines: yes
          plugins_errors_fatal: yes

      - name: Traffic plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.traffic.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: "repositories"
          plugin_traffic: yes
          plugins_errors_fatal: yes

      - name: Posts plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.posts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: ""
          plugin_posts: yes
          plugin_posts_source: dev.to
          plugins_errors_fatal: yes

      - name: Isocalendar plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugins_errors_fatal: yes

      - name: Isocalendar plugin (full year)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugins_errors_fatal: yes

      - name: Gists plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.gists.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: ""
          plugin_gists: yes
          plugins_errors_fatal: yes

      - name: Topics plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.topics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: ""
          plugin_topics: yes
          plugins_errors_fatal: yes

      - name: Projects plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.projects.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          committer_token: ${{ secrets.METRICS_BOT_TOKEN }}
          base: ""
          plugin_projects: yes
          plugins_errors_fatal: yes
